spring:
  datasource:
    username: postgres
    password: priya123
    url: jdbc:postgresql://localhost:5432/rental
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    enabled: false
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    placeholders:
      schema: ${spring.jpa.properties.hibernate.default_schema}
logging:
  file.name: /Users/priyavijayan/Documents/logs/application-debug.log
  level:
    root: DEBUG
    com.nbc.news.ip: DEBUG
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
toolrental:
  tool:
    CHNS : Chainsaw_Stihl
    LADW : Ladder_Werner
    JAKD : Jackhammer_DeWalt
    JAKR : Jackhammer_Ridgid   
  tooldailycharge:
    daily:
      Ladder : 1.99
      Chainsaw : 1.49
      Jackhammer : 2.99
    weekday:
      Ladder : true
      Chainsaw : true
      Jackhammer : true
    weekend:
      Ladder : true
      Chainsaw : false
      Jackhammer : false
    holiday:
      Ladder : false
      Chainsaw : true
      Jackhammer : false  